
###
###CRUD VEICULO
###


###CADASTRANDO VEICULO POR MEIO DO METODO POST
POST http://localhost:3001/veiculo/cadastrar
Content-Type: application/json

{
    "marca" : "Chevrolet",
    "modelo" : "Onix",
    "precoAluguel" : 100,
    "categoria" : "sedan",
    "status" : false,
    "integridade" : false,
    "combustivel" : 30
}


###ALTERA DADOS DE UM CARRO JA CADASTRADO
POST http://localhost:3001/veiculo/alterar
Content-Type: application/json

{
    "id" : 1,
    "marca" : "Gol",
    "modelo" : "Onix",
    "precoAluguel" : 200,
    "categoria" : "sedan",
    "status" : true,
    "integridade" : false,
    "combustivel" : 30
}

###EXCLUI UM CARRO JA CADASTRADO
DELETE http://localhost:3001/veiculo/excluir/1

###LISTA VEICULOS
GET http://localhost:3001/veiculo/listar

###ALUGAR VEICULO
POST http://localhost:3001/veiculo/alugar
Content-Type: application/json

{
    "cpf" : "333",
    "id" : 3
}



###DEVOLVE VEICULO
POST http://localhost:3001/veiculo/devolver
Content-Type: application/json

{
    "id" : 3,
    "combustivel" : 20,
    "integridade" : true
}



###
###CRUD CONDUTOR
###


###CADASTRANDO CONDUTOR POR MEIO DO METODO POST
POST http://localhost:3001/condutor/cadastrar
Content-Type: application/json

{
    "nome" : "MATHEUS",
    "idade" : 32,
    "dinheiro" : 2222,
    "alugando" : false
}

###ALTERA DADOS DE UM CADASTRADO JA CADASTRADO
###INSIRA UM CPF JA CADASTRADO, E ALTERE OS DADOS
POST http://localhost:3001/condutor/alterar
Content-Type: application/json

{
    "cpf" : "2",
    "nome" : "Victor",
    "idade" : 21,
    "alugando" : false

}

###EXCLUI UM CONDUTOR JA CADASTRADO
###INSIRA UM CPF JA CADASTRADO PARA SER EXCLUIDO
POST http://localhost:3001/condutor/excluir
Content-Type: application/json

{
    "cpf" : "2"
}

###LISTA CONDUTORES
GET http://localhost:3001/condutor/listar